menu(where=sel.count>0 type='namespace|back' mode='multiple' vis=@if(key.shift() || key.control(), "hidden", "normal") title='Valorant')
{
    item(title='Decoy' tip=['Platinum 2', tip.#3ab5c2, 0.0] cmd='"C:\Program Files\Python312\pythonw.exe"' args='"D:\Test playground\iMA SWITCHER\4 iMA-Switcher - Release 0.1 - Copy (3)\main.pyw" --switch "Decoy"' icon='C:\Users\iMA\AppData\Local\iMA Switcher\profiles\Decoy\icon.png')
    item(title='Gemini' tip=['Diamond 1', tip.#b584e0, 0.0] cmd='"C:\Program Files\Python312\pythonw.exe"' args='"D:\Test playground\iMA SWITCHER\4 iMA-Switcher - Release 0.1 - Copy (3)\main.pyw" --switch "Gemini"' icon='C:\Users\iMA\AppData\Local\iMA Switcher\profiles\Gemini\icon.png')
    item(title='Google' tip=['Gold 3', tip.#ecce6e, 0.0] cmd='"C:\Program Files\Python312\pythonw.exe"' args='"D:\Test playground\iMA SWITCHER\4 iMA-Switcher - Release 0.1 - Copy (3)\main.pyw" --switch "Google"' icon='C:\Users\iMA\AppData\Local\iMA Switcher\profiles\Google\icon.png')
    item(title='iMA' tip=['Platinum 2', tip.#3ab5c2, 0.0] cmd='"C:\Program Files\Python312\pythonw.exe"' args='"D:\Test playground\iMA SWITCHER\4 iMA-Switcher - Release 0.1 - Copy (3)\main.pyw" --switch "iMA"' icon='C:\Users\iMA\AppData\Local\iMA Switcher\profiles\iMA\icon.png')
    item(title='iMSteam' tip=['Unranked', tip.#4f555a, 0.0] cmd='"C:\Program Files\Python312\pythonw.exe"' args='"D:\Test playground\iMA SWITCHER\4 iMA-Switcher - Release 0.1 - Copy (3)\main.pyw" --switch "iMSteam"' icon='C:\Users\iMA\AppData\Local\iMA Switcher\profiles\iMSteam\icon.png')
    item(title='iMungus' tip=['Unranked', tip.#4f555a, 0.0] cmd='"C:\Program Files\Python312\pythonw.exe"' args='"D:\Test playground\iMA SWITCHER\4 iMA-Switcher - Release 0.1 - Copy (3)\main.pyw" --switch "iMungus"' icon='C:\Users\iMA\AppData\Local\iMA Switcher\profiles\iMungus\icon.png')
    item(title='Mr Milchick' tip=['Gold 2', tip.#ecce6e, 0.0] cmd='"C:\Program Files\Python312\pythonw.exe"' args='"D:\Test playground\iMA SWITCHER\4 iMA-Switcher - Release 0.1 - Copy (3)\main.pyw" --switch "Mr Milchick"' icon='C:\Users\iMA\AppData\Local\iMA Switcher\profiles\Mr Milchick\icon.png')
    item(title='Pixel' tip=['Platinum 2', tip.#3ab5c2, 0.0] cmd='"C:\Program Files\Python312\pythonw.exe"' args='"D:\Test playground\iMA SWITCHER\4 iMA-Switcher - Release 0.1 - Copy (3)\main.pyw" --switch "Pixel"' icon='C:\Users\iMA\AppData\Local\iMA Switcher\profiles\Pixel\icon.png')
}